spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/product
    username: rootuser
    password: rootuser
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 9094

